---
variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 0
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE

stages:
  - build

.build_container:
  stage: build
  services:
    - name: docker:dind
      command: ["--registry-mirror", "https://registry-mirror.example.com"]
  artifacts:
    expire_in: 1 week
  image:
    name: docker
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'

Build Container Image:
  extends: .build_container
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest-build || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest-build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest-build .
    - docker push $CI_REGISTRY_IMAGE:latest-build
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest-build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
